// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GeoPoint {
    #[prost(double, tag = "1")]
    pub latitude: f64,
    #[prost(double, tag = "2")]
    pub longitude: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LocationMetrics {
    #[prost(float, tag = "1")]
    pub accuracy: f32,
    #[prost(message, optional, tag = "2")]
    pub altitude: ::core::option::Option<f32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MovementMetrics {
    #[prost(float, tag = "1")]
    pub speed: f32,
    #[prost(float, tag = "2")]
    pub heading: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserLocation {
    #[prost(string, tag = "1")]
    pub profile_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub region_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub coordinates: ::core::option::Option<GeoPoint>,
    #[prost(message, optional, tag = "5")]
    pub metrics: ::core::option::Option<LocationMetrics>,
    #[prost(message, optional, tag = "6")]
    pub movement: ::core::option::Option<MovementMetrics>,
    #[prost(bool, tag = "7")]
    pub is_ghost_mode: bool,
    #[prost(int32, tag = "8")]
    pub privacy_radius_meters: i32,
    #[prost(message, optional, tag = "9")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "10")]
    pub version: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserLocationRequest {
    #[prost(string, tag = "1")]
    pub account_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePositionRequest {
    #[prost(string, tag = "1")]
    pub profile_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region_code: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub coordinates: ::core::option::Option<GeoPoint>,
    #[prost(message, optional, tag = "4")]
    pub metrics: ::core::option::Option<LocationMetrics>,
    #[prost(message, optional, tag = "5")]
    pub movement: ::core::option::Option<MovementMetrics>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetGhostModeRequest {
    #[prost(string, tag = "1")]
    pub profile_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region_code: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePrivacyRadiusRequest {
    #[prost(string, tag = "1")]
    pub profile_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub region_code: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub radius_meters: i32,
}
/// Generated client implementations.
pub mod location_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct LocationServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl LocationServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> LocationServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LocationServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LocationServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_user_location(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserLocationRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/location.v1.LocationService/GetUserLocation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("location.v1.LocationService", "GetUserLocation"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_position(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdatePositionRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/location.v1.LocationService/UpdatePosition",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("location.v1.LocationService", "UpdatePosition"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_ghost_mode(
            &mut self,
            request: impl tonic::IntoRequest<super::SetGhostModeRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/location.v1.LocationService/SetGhostMode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("location.v1.LocationService", "SetGhostMode"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_privacy_radius(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdatePrivacyRadiusRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/location.v1.LocationService/UpdatePrivacyRadius",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("location.v1.LocationService", "UpdatePrivacyRadius"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod location_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with LocationServiceServer.
    #[async_trait]
    pub trait LocationService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_user_location(
            &self,
            request: tonic::Request<super::GetUserLocationRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status>;
        async fn update_position(
            &self,
            request: tonic::Request<super::UpdatePositionRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status>;
        async fn set_ghost_mode(
            &self,
            request: tonic::Request<super::SetGhostModeRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status>;
        async fn update_privacy_radius(
            &self,
            request: tonic::Request<super::UpdatePrivacyRadiusRequest>,
        ) -> std::result::Result<tonic::Response<super::UserLocation>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct LocationServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> LocationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for LocationServiceServer<T>
    where
        T: LocationService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/location.v1.LocationService/GetUserLocation" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserLocationSvc<T: LocationService>(pub Arc<T>);
                    impl<
                        T: LocationService,
                    > tonic::server::UnaryService<super::GetUserLocationRequest>
                    for GetUserLocationSvc<T> {
                        type Response = super::UserLocation;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserLocationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocationService>::get_user_location(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserLocationSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/location.v1.LocationService/UpdatePosition" => {
                    #[allow(non_camel_case_types)]
                    struct UpdatePositionSvc<T: LocationService>(pub Arc<T>);
                    impl<
                        T: LocationService,
                    > tonic::server::UnaryService<super::UpdatePositionRequest>
                    for UpdatePositionSvc<T> {
                        type Response = super::UserLocation;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdatePositionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocationService>::update_position(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdatePositionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/location.v1.LocationService/SetGhostMode" => {
                    #[allow(non_camel_case_types)]
                    struct SetGhostModeSvc<T: LocationService>(pub Arc<T>);
                    impl<
                        T: LocationService,
                    > tonic::server::UnaryService<super::SetGhostModeRequest>
                    for SetGhostModeSvc<T> {
                        type Response = super::UserLocation;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetGhostModeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocationService>::set_ghost_mode(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetGhostModeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/location.v1.LocationService/UpdatePrivacyRadius" => {
                    #[allow(non_camel_case_types)]
                    struct UpdatePrivacyRadiusSvc<T: LocationService>(pub Arc<T>);
                    impl<
                        T: LocationService,
                    > tonic::server::UnaryService<super::UpdatePrivacyRadiusRequest>
                    for UpdatePrivacyRadiusSvc<T> {
                        type Response = super::UserLocation;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdatePrivacyRadiusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as LocationService>::update_privacy_radius(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdatePrivacyRadiusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for LocationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "location.v1.LocationService";
    impl<T> tonic::server::NamedService for LocationServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
