#  infrastructure/argocd/templates/karpenter.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.0.1
    helm:
      values: |
        settings:
          clusterName: {{ .Values.global.clusterName }}
          interruptionQueue: Karpenter-{{ .Values.global.clusterName }}
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: "{{ .Values.global.karpenterRoleArn }}"
        controller:
          clusterEndpoint: {{ .Values.global.clusterEndpoint }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true