# infrastructure/argocd/templates/monitoring.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.x.x
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              external-dns.alpha.kubernetes.io/hostname: grafana.core-platform.click
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/certificate-arn: {{ .Values.global.certificateArn }}
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
            hosts:
              - grafana.core-platform.click
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true