# infrastructure/argocd/apps/infrastructure/plateform/karpenter/values.yaml

karpenter:
  settings:
    clusterName: "core-platform-dev"
    interruptionQueue: "core-platform-dev" 
  serviceAccount:
    create: true
    name: karpenter