// backend/services/profile/api/event-worker/tests/worker_it.rs

use chrono::Utc;
use infra_kafka::KafkaEventProducer;
use profile::repositories::ProfileRepository;
use profile::stores::ScyllaProfileStore;
use profile_test_utils::ProfileTestContext;
use serde_json::json;
use shared_kernel::core::Result;
use shared_kernel::messaging::{EventEnvelope, EventProducer};
use shared_kernel::types::{AccountId, Region};
use uuid::Uuid;

#[tokio::test]
async fn test_worker_e2e_profile_creation_on_account_event() -> Result<()> {
    let _ = tracing_subscriber::fmt::try_init();

    // 1. SETUP INFRA ET BOOT DU WORKER VIA LA CLOSURE DU BUILDER (Testcontainers)
    let ctx = ProfileTestContext::builder()
        .with_kafka_worker()
        .build_e2e()
        .await;

    // Récupération sécurisée des bootstrap_servers de l'infra unifiée pour émettre notre événement
    let bootstrap_servers = ctx.kernel().kafka().bootstrap_servers().to_string();

    // 2. INITIALISATION DU PRODUCER OFFICIEL
    let kafka_producer = KafkaEventProducer::new(&bootstrap_servers, "account.events".to_string())
        .await
        .expect("Failed to create KafkaEventProducer");

    // 3. ACT : On crée l'enveloppe et le payload conformes au format d'AccountRegistered
    let region_str = "EU";
    let local_region = Region::try_from(region_str).unwrap();

    let real_account_id = AccountId::generate();
    let account_id_string = real_account_id.to_string();

    let account_registered_payload = json!({
        "type": "AccountRegistered",
        "data": {
            "account_id": account_id_string,
            "region": region_str,
            "email": "charlie_brown@peanuts.com",
            "phone": null,
            "sub_id": json!(Uuid::new_v4().to_string()),
            "locale": "en_US",
            "ip_addr": "127.0.0.1",
            "occurred_at": Utc::now().to_rfc3339()
        }
    });

    let envelope = EventEnvelope {
        id: Uuid::new_v4(),
        event_type: "account.identity.registered".to_string(),
        occurred_at: Utc::now(),
        region: region_str.to_string(),
        aggregate_type: "account".to_string(),
        aggregate_id: account_id_string.clone(),
        payload: account_registered_payload,
        metadata: None,
    };

    tracing::info!(account_id = %account_id_string, "Publishing true AccountRegistered event using KafkaEventProducer...");
    kafka_producer
        .publish(&envelope)
        .await
        .expect("Failed to publish event");

    // 4. INSTANCIATION DU STORE OFFICIEL POUR LES ASSERTIONS (ScyllaDB)
    let session = ctx.kernel().scylla().session();

    // Calcul du nom du keyspace régional pour ce test E2E éphémère
    let keyspace_name = format!(
        "{}_profile_storage",
        local_region.to_string().to_lowercase()
    );

    let profile_store = ScyllaProfileStore::new(session.clone(), keyspace_name)
        .await
        .expect("Failed to initialize ScyllaProfileStore for verification");

    // 5. ASYNC WAIT / ASSERT (Eventual Consistency de Kafka/ScyllaDB)
    let expected_handle = format!("user_{}", &account_id_string[0..8]);
    let mut profile_created = false;

    for _ in 0..100 {
        let profiles = profile_store
            .find_all_by_account_id(real_account_id)
            .await
            .unwrap();

        if let Some(profile) = profiles.first() {
            assert_eq!(
                profile.handle().as_str(),
                expected_handle,
                "Le handle créé par le worker ne respecte pas le format autogénéré attendu"
            );
            tracing::info!(handle = %profile.handle().as_str(), "Profile successfully found in ScyllaDB with autogenerated handle!");
            profile_created = true;
            break;
        }

        tokio::time::sleep(tokio::time::Duration::from_millis(50)).await;
    }

    assert!(
        profile_created,
        "The worker failed to process the AccountRegistered message published by KafkaEventProducer"
    );

    ctx.shutdown().await;
    Ok(())
}
