// backend/services/profile/api/event-worker/tests/worker_it.rs

use chrono::Utc;
use infra_kafka::KafkaEventProducer;
use infra_sqlx::sqlx;
use profile_test_utils::ProfileTestContext;
use serde_json::json;
use shared_kernel::core::Result;
use shared_kernel::messaging::{EventEnvelope, EventProducer};
use shared_kernel::types::{AccountId, Region};
use uuid::Uuid;

#[tokio::test]
async fn test_worker_e2e_profile_creation_on_account_event() -> Result<()> {
    let _ = tracing_subscriber::fmt::try_init();

    // 1. SETUP INFRA ET BOOT DU WORKER VIA LA CLOSURE DU BUILDER
    let ctx = ProfileTestContext::builder()
        .with_kafka_worker()
        .build_e2e()
        .await;
 
    // Récupération sécurisée des bootstrap_servers de l'infra unifiée pour émettre notre événement
    let bootstrap_servers = ctx.kernel().kafka().bootstrap_servers().to_string();

    // 2. INITIALISATION DU PRODUCER OFFICIEL
    let kafka_producer = KafkaEventProducer::new(&bootstrap_servers, "account.events".to_string())
        .await
        .expect("Failed to create KafkaEventProducer");

    // 3. ACT : On crée l'enveloppe et le payload conformes au format d'AccountRegistered
    let region_str = "EU";
    let region = Region::try_new(region_str)?;

    // 💡 FIX : On utilise ton vrai Smart ID typé pour générer un identifiant valide pour le domaine !
    let real_account_id = AccountId::generate();
    let account_id_string = real_account_id.to_string();
    let account_uuid = real_account_id.uuid(); // Pour l'interrogation SQLx plus bas

    let account_registered_payload = json!({
        "type": "AccountRegistered",
        "data": {
            "account_id": account_id_string,
            "region": region_str,
            "email": "charlie_brown@peanuts.com",
            "phone": null,
            "sub_id": json!(Uuid::new_v4().to_string()),
            "locale": "en_US",
            "ip_addr": "127.0.0.1",
            "occurred_at": Utc::now().to_rfc3339()
        }
    });

    let envelope = EventEnvelope {
        id: Uuid::new_v4(),
        event_type: "account.identity.registered".to_string(),
        occurred_at: Utc::now(),
        region: region_str.to_string(),
        aggregate_type: "account".to_string(),
        aggregate_id: account_id_string.clone(),
        payload: account_registered_payload,
        metadata: None,
    };

    tracing::info!(account_id = %account_id_string, "Publishing true AccountRegistered event using KafkaEventProducer...");
    kafka_producer
        .publish(&envelope)
        .await
        .expect("Failed to publish event");

    // 4. ASYNC WAIT / ASSERT
    let expected_handle = format!("user_{}", &account_id_string[0..8]);
    let mut profile_created = false;

    for _ in 0..100 {
        let row: Option<(String,)> =
            sqlx::query_as("SELECT handle FROM user_profiles WHERE account_id = $1")
                .bind(account_uuid) // 💡 On lie le UUID brut ou le format attendu par ton schéma SQL
                .fetch_optional(&ctx.pg_pool())
                .await
                .unwrap();

        if let Some(r) = row {
            assert_eq!(
                r.0, expected_handle,
                "Le handle créé ne respecte pas le format autogénéré attendu"
            );
            tracing::info!(handle = %r.0, "Profile successfully found in database with autogenerated handle!");
            profile_created = true;
            break;
        }
        tokio::time::sleep(tokio::time::Duration::from_millis(50)).await;
    }

    assert!(
        profile_created,
        "The worker failed to process the AccountRegistered message published by KafkaEventProducer"
    );

    ctx.shutdown().await;
    Ok(())
}
