# .github/workflows/k6-test-build.yaml

name: Build and Push k6 Load Test Image

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'proto/**'
      - 'backend/services/profile/api/command-server/load-tests/**'
      - 'Dockerfile.k6'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: core-platform-k6-tests
          IMAGE_TAG: latest # Tu pourrais utiliser le GITHUB_SHA pour plus de précision
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.k6 .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Refresh ArgoCD (Optional)
        run: |
          # Si tu as installé l'ArgoCD CLI, tu peux forcer un refresh ici
          # Sinon, ArgoCD détectera le changement au bout de 3 min max
          echo "Image pushed. ArgoCD will sync the new image automatically."